[build-system]
requires = ['poetry-core>=1.0.0', 'wheel',]
build-backend = 'poetry.core.masonry.api'


[tool.coverage.run]
branch = true
relative_files = true
omit = [
    '.tox/*',
    'tests/*',
]


[tool.flake8]
max-line-length = 120
extend-ignore = ''  # https://www.flake8rules.com/
max-complexity = 15  # Info: https://en.wikipedia.org/wiki/Cyclomatic_complexity
per-file-ignores = """\
# F401: Ignore "unused" imports
# F403: Ignore star imports
# F405: Ignore names from star imports
__init__.py:F401,F403,F405\
"""


[tool.poetry]
name = 'rl_car'
version = '0.1.0'
description = "A template Poetry project structure."

authors = ["Lari Liuhamo <lari.liuhamo+pypi@gmail.com>",]
maintainers = ["Lari Liuhamo <lari.liuhamo+pypi@gmail.com>",]

include = ['CHANGELOG.md', 'LICENSE',]
license = 'MIT'
readme = 'README.md'

homepage = 'https://pypi.org/project/rl_car/'
repository = 'https://github.com/Diapolo10/rl_car'
documentation = 'https://github.com/Diapolo10/rl_car/tree/main/docs'

keywords = [
    'python3',
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: Implementation :: CPython',
    'Typing :: Typed',
]


[tool.poetry.dependencies]
python = '~3.8'
arcade = '^2.6.7'
numpy = '^1.18.5'
tensorflow = '^2.3.4'


[tool.poetry.dev-dependencies]
coverage = {version = '^6.2', extras = ['toml',]}
flake8 = '^3.9.2'
mypy = '^0.941'
pylint = '^2.6.2'
pyproject-flake8 = '^0.0.1a2'
pytest = '^7.0.1'
pytest-cov = '^3.0.0'
tox = '^3.24.5'
tox-gh-actions = '^2.9.1'


[tool.poetry.urls]
"Source code" = 'https://github.com/Diapolo10/rl_car'
"Tracker" = 'https://github.com/Diapolo10/rl_car/issues'
"Changelog" = 'https://github.com/Diapolo10/rl_car/blob/main/CHANGELOG.md'


[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = [
    # https://vald-phoenix.github.io/pylint-errors/
]


[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
--doctest-modules \
--cov=./ \
--cov-append \
--cov-report html:tests/reports/coverage-html \
--cov-report xml:tests/reports/coverage.xml \
--ignore=docs/
"""
testpaths = [
    'tests',
]


[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38, py39, pypy3
isolated_build = True

[gh-actions]
python =
    3.6: py36
    3.7: py37
    3.8: py38
    3.9: py39
    pypy-3.7: pypy3

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos
    windows-latest: windows

[testenv]
passenv = GITHUB_*
deps =
    coverage
    coveralls[toml]
    pytest
    pytest-cov
    wheel
commands =
    coverage run -m pytest
"""
