[build-system]
requires = ["poetry-core>=1.2.0", "wheel"]
build-backend = "poetry.core.masonry.api"


[tool.coverage.run]
branch = true
relative_files = true
omit = [".tox/*", "tests/*"]


[tool.poetry]
name = "rl_car"
version = "0.2.0"
description = "Let's teach an AI to drive - using reinforcement learning."

packages = [{ include = "rl_car", from = "src" }]

authors = ["Lari Liuhamo <lari.liuhamo+pypi@gmail.com>"]
maintainers = ["Lari Liuhamo <lari.liuhamo+pypi@gmail.com>"]

include = ["CHANGELOG.md", "LICENSE", "py.typed"]
license = "MIT"
readme = "README.md"

homepage = "https://pypi.org/project/rl_car/"
repository = "https://github.com/Diapolo10/rl_car"
documentation = "https://github.com/Diapolo10/rl_car/tree/main/docs"

keywords = ["python3"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Education",
    "Topic :: Games/Entertainment :: Arcade",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Visualization",
    "Typing :: Typed",
]


[tool.poetry.dependencies]
python = "^3.12,<3.15"
arcade = "^3.3.3"
# grpcio = "^1.60.0"
numpy = "^2.4.4"
shapely = "^2.1.2"
torch = "^2.11.0"
# tensorflow = "~2.11.0"  # Last known version with Windows support
# tensorflow-io-gcs-filesystem = "~0.35.0"  # Ditto


[tool.poetry.group.dev.dependencies]
mypy = ">=2.1.0"


[tool.poetry.group.linters]
optional = true


[tool.poetry.group.linters.dependencies]
ruff = ">=0.15.12,<0.17.0"


[tool.poetry.group.tests]
optional = true


[tool.poetry.group.tests.dependencies]
pytest = "^9.0.3"
pytest-cov = "^7.1.0"
tox = "^4.53.1"
tox-gh-actions = "^3.5.0"


[tool.poetry.urls]
"Source code" = "https://github.com/Diapolo10/rl_car"
"Tracker" = "https://github.com/Diapolo10/rl_car/issues"
"Changelog" = "https://github.com/Diapolo10/rl_car/blob/main/CHANGELOG.md"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
--doctest-modules \
--cov=./ \
--cov-append \
--cov-report html:tests/reports/coverage-html \
--cov-report xml:tests/reports/coverage.xml \
--ignore=docs/
"""
testpaths = ["tests"]

[tool.ruff]
line-length = 120
show-fixes = true
src = ["src"]
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN001",  # Missing type annotation for parameter in method
    "ARG002",  # Unused argument
    "CPY",     # Missing copyright notice
    "D203",    # One blank line before class docstring
    "D212",    # Multi-line summary first line
    "FIX002",  # TODO found
    "PLR0913", # Too many arguments
    "Q000",    # Single quotes found but double quotes preferred
    "T201",    # print found
    "TD002",   # Missing author for TODO
    "TD003",   # Missing issue link for TODO
]


[tool.ruff.lint.mccabe]
max-complexity = 10


[tool.ruff.lint.per-file-ignores]
# https://beta.ruff.rs/docs/rules/
"__init__.py" = ["F401", "F403", "F405"]
"tests/*" = ["ANN", "ARG", "INP001", "S101"]


[tool.ruff.lint.pylint]
max-args = 15
max-branches = 20
max-returns = 10
max-statements = 80


[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"


[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py3{12, 13, 14}, pypy3
skip_missing_interpreters = true

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314
    pypy-3.12: pypy3

[testenv]
passenv = GITHUB_*
allowlist_externals = poetry

commands =
    poetry run pytest
    poetry run coverage report
"""
